POST /api/2.3/tenders/a48337f6bad64080a9f69f830514e059/bids HTTP/1.0
Authorization: Basic YnJva2VyOg==
Content-Length: 888
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "selfEligible": true, 
    "selfQualified": true, 
    "value": {
      "amount": 500
    }, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "countryName": "Україна", 
          "postalCode": "01220", 
          "region": "м. Київ", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "locality": "м. Київ"
        }
      }
    ]
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/a48337f6bad64080a9f69f830514e059/bids/55f611dd2f7c498891e3ceb7306f26d6
{
  "access": {
    "transfer": "e01de596a11e4b519005c3ba26c3bdc1", 
    "token": "b2c4014e306943508f0a4fdc4c3e4a33"
  }, 
  "data": {
    "status": "pending", 
    "selfEligible": true, 
    "value": {
      "currency": "UAH", 
      "amount": 500.0, 
      "valueAddedTaxIncluded": true
    }, 
    "selfQualified": true, 
    "tenderers": [
      {
        "contactPoint": {
          "name": "Державне управління справами", 
          "telephone": "0440000000"
        }, 
        "identifier": {
          "scheme": "UA-EDR", 
          "id": "00037256", 
          "uri": "http://www.dus.gov.ua/"
        }, 
        "name": "Державне управління справами", 
        "address": {
          "postalCode": "01220", 
          "countryName": "Україна", 
          "streetAddress": "вул. Банкова, 11, корпус 1", 
          "region": "м. Київ", 
          "locality": "м. Київ"
        }
      }
    ], 
    "date": "2016-10-31T12:16:10.278984+02:00", 
    "id": "55f611dd2f7c498891e3ceb7306f26d6"
  }
}

