POST /api/2.3/tenders/19243d1faf904243941a9eb1a517e7c7/awards/5b8aed9a411c49c0b81e02ba17adea56/complaints?acc_token=b37f411b662d495ebd9821b5fee390c6 HTTP/1.0
Authorization: Basic YnJva2VyMjo=
Content-Length: 899
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {
    "status": "claim", 
    "title": "complaint title", 
    "description": "complaint description", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "countryName": "Україна", 
        "postalCode": "01220", 
        "region": "м. Київ", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "locality": "м. Київ"
      }
    }
  }
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
Location: http://api-sandbox.openprocurement.org/api/2.3/tenders/19243d1faf904243941a9eb1a517e7c7/awards/5b8aed9a411c49c0b81e02ba17adea56/complaints/53d2ff9160924d24ab323cc3163129ca
{
  "access": {
    "transfer": "8aca5cf1d889494abf375bf2a29d56fb", 
    "token": "373b86f03f3c4d4a94386f918c8a4707"
  }, 
  "data": {
    "status": "claim", 
    "description": "complaint description", 
    "title": "complaint title", 
    "author": {
      "contactPoint": {
        "name": "Державне управління справами", 
        "telephone": "0440000000"
      }, 
      "identifier": {
        "scheme": "UA-EDR", 
        "id": "00037256", 
        "uri": "http://www.dus.gov.ua/"
      }, 
      "name": "Державне управління справами", 
      "address": {
        "postalCode": "01220", 
        "countryName": "Україна", 
        "streetAddress": "вул. Банкова, 11, корпус 1", 
        "region": "м. Київ", 
        "locality": "м. Київ"
      }
    }, 
    "dateSubmitted": "2016-09-12T14:16:25.910153+03:00", 
    "complaintID": "UA-2016-09-12-000001.2", 
    "date": "2016-09-12T14:16:25.910121+03:00", 
    "type": "claim", 
    "id": "53d2ff9160924d24ab323cc3163129ca"
  }
}

