POST /api/2.3/transfers HTTP/1.0
Authorization: Basic YnJva2VyNDo=
Content-Length: 12
Content-Type: application/json
Host: api-sandbox.openprocurement.org
DATA:
{
  "data": {}
}

Response: 201 Created
Content-Type: application/json; charset=UTF-8
{
  "access": {
    "transfer": "76539baec6414b02a2d7cf2bec55870d", 
    "token": "e91eb2c19fc244b5a78e7b6c5bdfa81c"
  }, 
  "data": {
    "date": "2016-11-01T11:01:23.877124+02:00", 
    "id": "413ef5e46cf4d07822bb1bb7ae0690d7"
  }
}

